blank_issues_enabled: false
contact_links:
  - name: We've moved ➡️
    url: https://github.com/CommunityToolkit/Windows/issues/new/choose
    about: "Please file your issue in the new repository."
  - name: MVVM Toolkit, High Performance, or Diagnostic Package? 
    url: https://aka.ms/toolkit/dotnet
    about: "If you have a question on these, see the .NET Community Toolkit repo:"
  